export interface StudentInterface {
    _id?:string,
    rollNumber:string,
    courseName:string,
    department:string,
    admisionDate:string,
    vallidDate:string,
    name:string,
    email:string,
    address:string,
    phoneNumber:string,
    password:string,
    dob:string,
    date_time:string,
}